source 'https://github.com/CocoaPods/Specs.git'

target 'KMMTMDBAPIClient', :exclusive => true do
  pod "KMMTMDBAPIClient", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "KMMTMDBAPIClient", :path => "../"

  
end
